### ISSUE TITLE
Intro & Ending Game Screens

### ISSUE THREAD

**Issue by Staethe** [wonga6/GameDev1_Project2#4]
Stills to provide context to scenario: one set will be played at the opening, one set will be played upon successful completion of the game. In addition, a separate game over screen is needed for when the player runs out of lives.

- [x] Opening Stills
- [x] Game Over Screen
- [x] Ending Stills

REACH
- [x] Opening Play Screen

**Comment by Staethe** [comment]
Programmers need to research & confirm capabilities.

**Comment by Mijumaru3** [comment]
Implemented changing scenes from Intro (which will show the stills) to the Game to Game Over

**Comment by Staethe** [comment]
Programming logic is done for this (mijumaru3 finished implementation). Can be closed when play & game over screens are done @Ferrohound  @CuriousHatty
